### ISSUE TITLE
Not support for laravel 5.1 version

### ISSUE THREAD

**Issue by AnandhamK** [Superbalist/laravel-pubsub#8]
I am getting error to Run "composer require superbalist/laravel-pubsub"

 Problem 1
    - Conclusion: remove laravel/framework v5.1.46
    - Conclusion: don't install laravel/framework v5.1.46
    - superbalist/laravel-pubsub 2.0.0 requires illuminate/console ^5.3 -> satisfiable by illuminate/console[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.9].
    - superbalist/laravel-pubsub 2.0.1 requires illuminate/console ^5.3 -> satisfiable by illuminate/console[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.9].
    - don't install illuminate/console v5.3.0|don't install laravel/framework v5.1.46
    - don't install illuminate/console v5.3.16|don't install laravel/framework v5.1.46
    - don't install illuminate/console v5.3.23|don't install laravel/framework v5.1.46
    - don't install illuminate/console v5.3.4|don't install laravel/framework v5.1.46
    - don't install illuminate/console v5.4.0|don't install laravel/framework v5.1.46
    - don't install illuminate/console v5.4.13|don't install laravel/framework v5.1.46
    - don't install illuminate/console v5.4.17|don't install laravel/framework v5.1.46
    - don't install illuminate/console v5.4.9|don't install laravel/framework v5.1.46
    - Installation request for laravel/framework (locked at v5.1.46, required as 5.1.*) -> satisfiable by laravel/framework[v5.1.46].
    - Installation request for superbalist/laravel-pubsub ^2.0 -> satisfiable by superbalist/laravel-pubsub[2.0.0, 2.0.1].

**Comment by matthewgoslett** [comment]
We unfortunately only have support for 5.3+ up until 2.0.2.
2.0.3 and up now supports Laravel 5.4 because of their breaking change on the container interface where they removed the ability to pass params to ->make() and introduced the new ->makeWIth() method.
